# Generated by Django 2.2 on 2019-04-08 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=120, null=True)),
                ('quesionPaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.QuestionPaper')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.CharField(blank=True, max_length=120, null=True)),
                ('questionImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('option1text', models.CharField(blank=True, max_length=120, null=True)),
                ('option1image', models.ImageField(blank=True, null=True, upload_to='')),
                ('option2text', models.CharField(blank=True, max_length=120, null=True)),
                ('option2image', models.ImageField(blank=True, null=True, upload_to='')),
                ('option3text', models.CharField(blank=True, max_length=120, null=True)),
                ('option3image', models.ImageField(blank=True, null=True, upload_to='')),
                ('option4text', models.CharField(blank=True, max_length=120, null=True)),
                ('option4image', models.ImageField(blank=True, null=True, upload_to='')),
                ('correctAnswer', models.CharField(blank=True, max_length=120, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('explanationImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('answer', models.CharField(blank=True, max_length=120, null=True)),
                ('questionPaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.QuestionPaper')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subjects')),
            ],
        ),
    ]
