# Generated by Django 2.2 on 2019-04-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190406_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaper',
            name='answer1Boolean',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='answer2Boolean',
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='option1text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='option2text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
