# Generated by Django 2.2 on 2019-04-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190406_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='answer',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('b', 'b'), ('c', 'c')], max_length=120, null=True),
        ),
    ]
