# Generated by Django 2.2 on 2019-04-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_questionpaper_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='answer',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
