# Generated by Django 2.2 on 2019-04-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190406_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='questionImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
