# Generated by Django 2.2 on 2019-04-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_questionpaper_questionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='option1image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='option2image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='option3image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='option4image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
