# Generated by Django 2.2 on 2019-04-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190406_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='correctAnswer',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='questionPaperName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
