# Generated by Django 2.2 on 2019-04-06 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190406_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionpaper',
            old_name='answer',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='correctAnswer',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='option1image',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='option1text',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='option2image',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='option2text',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='option3image',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='option3text',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='option4image',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='option4text',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='questionImage',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='questionPaperName',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='questionText',
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.CharField(blank=True, max_length=120, null=True)),
                ('questionImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('option1text', models.CharField(blank=True, max_length=120, null=True)),
                ('option1image', models.ImageField(blank=True, null=True, upload_to='')),
                ('option2text', models.CharField(blank=True, max_length=120, null=True)),
                ('option2image', models.ImageField(blank=True, null=True, upload_to='')),
                ('option3text', models.CharField(blank=True, max_length=120, null=True)),
                ('option3image', models.ImageField(blank=True, null=True, upload_to='')),
                ('option4text', models.CharField(blank=True, max_length=120, null=True)),
                ('option4image', models.ImageField(blank=True, null=True, upload_to='')),
                ('correctAnswer', models.CharField(blank=True, max_length=120, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('answer', models.CharField(blank=True, max_length=120, null=True)),
                ('questionPaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.QuestionPaper')),
            ],
        ),
    ]
