# Generated by Django 2.2 on 2019-04-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190406_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='explanationImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
